"use client";
import { useState, useTransition } from "react";
import { MessageCircle, PlusCircle } from "lucide-react";
import type { LoyaltyCounterState } from "@/app/admin/crm/loyalty/actions";
import { recordLoyaltyPurchase } from "@/app/admin/crm/loyalty/actions";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAdminLanguage } from "@/lib/admin-language";

export function LoyaltyCounter({ initialState }: { initialState: LoyaltyCounterState }) {
  const { language } = useAdminLanguage();
  const [phone, setPhone] = useState(""); const [ruleId, setRuleId] = useState(initialState.rules[0]?.id ?? "");
  const [result, setResult] = useState<any>(null); const [message, setMessage] = useState(initialState.message ?? null); const [pending, start] = useTransition();
  const copy = language === "fa" ? { title:"ثبت مصرف وفاداری", phone:"شماره تلفن", rule:"نوع شمارش", record:"ثبت مصرف", recent:"آخرین شمارش‌ها", whatsapp:"واتس‌اپ" } : language === "ar" ? { title:"تسجيل استهلاك الولاء", phone:"رقم الهاتف", rule:"نوع العداد", record:"تسجيل", recent:"أحدث العدادات", whatsapp:"واتساب" } : { title:"Record loyalty purchase", phone:"Phone number", rule:"Counter rule", record:"Record purchase", recent:"Recent counters", whatsapp:"WhatsApp" };
  const submit=()=>start(async()=>{const r=await recordLoyaltyPurchase({phone,ruleId}); setResult(r); setMessage(r.message ?? null);});
  const send=()=>{ if(!result?.rule) return; const template=language==="fa"?result.rule.messageFa:language==="ar"?result.rule.messageAr:result.rule.messageEn; const text=(template||`Dear customer, this is purchase ${result.count} of ${result.threshold}.`).replaceAll("{phone}",phone).replaceAll("{count}",String(result.count)).replaceAll("{threshold}",String(result.threshold)); window.open(`https://wa.me/${phone.replace(/[^0-9]/g,"")}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer"); };
  return <div className="space-y-5"><Card className="p-5"><h2 className="text-xl font-black text-[color:var(--admin-text)]">{copy.title}</h2>{message&&<p className="mt-2 text-sm text-amber-200">{message}</p>}<div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder={copy.phone} className="rounded-2xl border border-[color:var(--admin-border)] bg-black/10 px-4 py-3 text-sm text-[color:var(--admin-text)] outline-none"/><select value={ruleId} onChange={e=>setRuleId(e.target.value)} className="rounded-2xl border border-[color:var(--admin-border)] bg-black/10 px-4 py-3 text-sm text-[color:var(--admin-text)] outline-none"><option value="">{copy.rule}</option>{initialState.rules.map(r=><option key={r.id} value={r.id}>{r.name} · {r.thresholdCount}</option>)}</select><Button onClick={submit} disabled={pending||!phone||!ruleId}><PlusCircle className="h-4 w-4"/>{copy.record}</Button></div>{result?.success&&<div className="mt-4 flex items-center justify-between gap-3 rounded-2xl border border-emerald-300/20 bg-emerald-300/10 p-4"><div><p className="font-black text-[color:var(--admin-text)]">{result.rule.name}</p><p className="text-sm text-[color:var(--admin-muted)]">{result.count} / {result.threshold}{result.rewardReached?" · Reward reached":""}</p></div><Button onClick={send}><MessageCircle className="h-4 w-4"/>{copy.whatsapp}</Button></div>}</Card><Card className="p-5"><h3 className="text-lg font-black text-[color:var(--admin-text)]">{copy.recent}</h3><div className="mt-4 divide-y divide-[color:var(--admin-border)]">{initialState.counters.map(c=><div key={c.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-bold text-[color:var(--admin-text)]">{c.phone}</p><p className="text-xs text-[color:var(--admin-muted)]">{c.ruleName}</p></div><p className="font-black text-amber-200">{c.currentCount} · total {c.totalCount}</p></div>)}</div></Card></div>;
}
