"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { requireModulePermission } from "@/lib/user-permissions";

export type FeedbackRule = { id:string; band_key:string; min_score:number|null; max_score:number|null; response_method:string; response_value:number|null; free_item_text:string|null; message_fa:string; message_ar:string; message_en:string; request_google_review:boolean; is_active:boolean };
export type FeedbackSettingsState={success:boolean;message?:string;rules:FeedbackRule[];googleReviewUrl:string;googleReviewEnabled:boolean;googleTextFa:string;googleTextAr:string;googleTextEn:string};
export async function getFeedbackSettings():Promise<FeedbackSettingsState>{const ctx=await requireModulePermission("settings_feedback","view");const db:any=createSupabaseAdminClient();const [{data:rules,error},{data:biz},{data:g}]=await Promise.all([db.from("feedback_response_rules").select("*").eq("business_id",ctx.currentBusiness.id).order("sort_order"),db.from("businesses").select("google_maps_review_url").eq("id",ctx.currentBusiness.id).maybeSingle(),db.from("feedback_google_review_settings").select("*").eq("business_id",ctx.currentBusiness.id).maybeSingle()]);return {success:!error,message:error?.message,rules:rules||[],googleReviewUrl:biz?.google_maps_review_url||"",googleReviewEnabled:g?.is_enabled??true,googleTextFa:g?.message_fa||"",googleTextAr:g?.message_ar||"",googleTextEn:g?.message_en||""}}
export async function saveFeedbackRule(input:FeedbackRule){const ctx=await requireModulePermission("settings_feedback","edit");const db:any=createSupabaseAdminClient();const {error}=await db.from("feedback_response_rules").update({response_method:input.response_method,response_value:input.response_value,free_item_text:input.free_item_text,message_fa:input.message_fa,message_ar:input.message_ar,message_en:input.message_en,request_google_review:input.request_google_review,is_active:input.is_active,updated_at:new Date().toISOString()}).eq("id",input.id).eq("business_id",ctx.currentBusiness.id);if(error)return{success:false,message:error.message};revalidatePath("/admin/settings/feedback");return{success:true,message:"Saved"}}
export async function saveGoogleReviewSettings(input:{url:string;isEnabled:boolean;messageFa:string;messageAr:string;messageEn:string}){const ctx=await requireModulePermission("settings_feedback","edit");const db:any=createSupabaseAdminClient();const {error:e1}=await db.from("businesses").update({google_maps_review_url:input.url||null}).eq("id",ctx.currentBusiness.id);const {error:e2}=await db.from("feedback_google_review_settings").upsert({business_id:ctx.currentBusiness.id,is_enabled:input.isEnabled,message_fa:input.messageFa,message_ar:input.messageAr,message_en:input.messageEn,updated_at:new Date().toISOString()},{onConflict:"business_id"});if(e1||e2)return{success:false,message:e1?.message||e2?.message};revalidatePath("/admin/settings/feedback");return{success:true,message:"Saved"}}
