"use client";
import { useState,useTransition } from "react";
import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAdminLanguage } from "@/lib/admin-language";
import { saveWhatsAppTemplate,type WhatsAppTemplate } from "@/app/admin/settings/whatsapp-messages/actions";
const titles:Record<string,{fa:string;ar:string;en:string}>={feedback_high:{fa:"فیدبک: امتیاز 4 یا بیشتر",ar:"الآراء: تقييم 4 أو أكثر",en:"Feedback: score 4+"},feedback_mid:{fa:"فیدبک: بیشتر از 2 و کمتر از 4",ar:"الآراء: أكثر من 2 وأقل من 4",en:"Feedback: above 2 and below 4"},feedback_low:{fa:"فیدبک: امتیاز 2 یا کمتر",ar:"الآراء: تقييم 2 أو أقل",en:"Feedback: score 2 or lower"},followup:{fa:"پیگیری مشتری",ar:"متابعة العميل",en:"Customer follow-up"},discount_early:{fa:"کد تخفیف: بیشتر از 3 روز",ar:"كود الخصم: أكثر من 3 أيام",en:"Discount code: more than 3 days"},discount_expiry:{fa:"کد تخفیف: 3 روز یا کمتر",ar:"كود الخصم: 3 أيام أو أقل",en:"Discount code: 3 days or less"},cash_closing:{fa:"صندوق بسته‌شده",ar:"إغلاق الصندوق",en:"Cash closing"},invoice:{fa:"فاکتور",ar:"الفاتورة",en:"Invoice"},loyalty_progress:{fa:"وفاداری: هنوز به تارگت نرسیده",ar:"الولاء: لم يصل للهدف",en:"Loyalty: target not reached"},loyalty_reward:{fa:"وفاداری: جایزه آماده است",ar:"الولاء: المكافأة جاهزة",en:"Loyalty: reward available"}};
const copy={fa:{title:"متن‌های واتساپ",desc:"تمام دکمه‌های واتساپ سیستم متن خود را از این صفحه می‌خوانند.",fa:"فارسی",ar:"عربی",en:"انگلیسی",save:"ذخیره",active:"فعال"},ar:{title:"رسائل واتساب",desc:"جميع أزرار واتساب تقرأ النص من هذه الصفحة.",fa:"فارسي",ar:"عربي",en:"إنجليزي",save:"حفظ",active:"مفعل"},en:{title:"WhatsApp Messages",desc:"Every WhatsApp action in the system reads its message from this central page.",fa:"Persian",ar:"Arabic",en:"English",save:"Save",active:"Active"}};
export function WhatsAppTemplatesManager({initialState}:{initialState:{success:boolean;message?:string;templates:WhatsAppTemplate[]}}){const {language}=useAdminLanguage();const t=copy[language];const [rows,setRows]=useState(initialState.templates);const [pending,start]=useTransition();const input="w-full rounded-xl border border-[color:var(--admin-border)] bg-[color:var(--admin-soft)] p-3 text-sm text-[color:var(--admin-text)]";const upd=(id:string,p:Partial<WhatsAppTemplate>)=>setRows(x=>x.map(r=>r.id===id?{...r,...p}:r));return <div className="space-y-5"><Card className="p-6"><h1 className="text-2xl font-black text-[color:var(--admin-text)]">{t.title}</h1><p className="mt-2 text-sm text-[color:var(--admin-muted)]">{t.desc}</p></Card>{rows.map(r=><Card key={r.id} className="p-6"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-black text-[color:var(--admin-text)]">{titles[r.template_key]?.[language]||r.label}</h2><label className="flex items-center gap-2 text-sm text-[color:var(--admin-muted)]"><input type="checkbox" checked={r.is_active} onChange={e=>upd(r.id,{is_active:e.target.checked})}/>{t.active}</label></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><label><span className="mb-2 block text-xs font-bold text-[color:var(--admin-muted)]">{t.fa}</span><textarea rows={7} className={input} value={r.message_fa} onChange={e=>upd(r.id,{message_fa:e.target.value})}/></label><label><span className="mb-2 block text-xs font-bold text-[color:var(--admin-muted)]">{t.ar}</span><textarea rows={7} className={input} value={r.message_ar} onChange={e=>upd(r.id,{message_ar:e.target.value})}/></label><label><span className="mb-2 block text-xs font-bold text-[color:var(--admin-muted)]">{t.en}</span><textarea rows={7} className={input} value={r.message_en} onChange={e=>upd(r.id,{message_en:e.target.value})}/></label></div><div className="mt-4 flex justify-end"><Button onClick={()=>start(async()=>{ await saveWhatsAppTemplate(r); })} disabled={pending}><Save className="h-4 w-4"/>{t.save}</Button></div></Card>)}</div>}
